Sylius\Component\Product\Model\ProductVariant:
    exclusion_policy: ALL
    xml_root_name: variant
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, DetailedCart, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart, Autocomplete]
        position:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        optionValues:
            expose: true
            type: array
            groups: [Default, Detailed, DetailedCart]
        translations:
            expose: true
            type: array
            groups: [Default, Detailed, DetailedCart]
    virtual_properties:
        getDescriptor:
            serialized_name: descriptor
            groups: [Autocomplete]
    relations:
        -   rel: self
            href:
                route: sylius_admin_api_product_variant_show
                parameters:
                    code: expr(object.getCode())
                    productCode: expr(object.getProduct().getCode())
                    version: 1
        -   rel: product
            href:
                route: sylius_admin_api_product_show
                parameters:
                    code: expr(object.getProduct().getCode())
                    version: 1
            exclusion:
                groups: [Detailed]
