Sylius\Component\Order\Model\OrderItem:
    exclusion_policy: ALL
    xml_root_name: order
    properties:
        id:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        quantity:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        unitPrice:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        total:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        units:
            expose: true
            type: array
            groups: [Default, Detailed, DetailedCart]
        unitsTotal:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        adjustments:
            expose: true
            type: array
            groups: [Default, Detailed, DetailedCart]
        adjustmentsTotal:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
    relations:
        - rel: order
          exclusion:
            groups: [Default, Detailed, DetailedCart]
          href:
                route: sylius_admin_api_order_show
                parameters:
                    id: expr(object.getOrder().getId())
                    version: 1
