security:
    providers:
        bigfoot:
            entity:
                class: BigfootUserBundle:User

    encoders:
        Bigfoot\Bundle\UserBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000

    firewalls:
        login_firewall:
            pattern: ^/admin/login$
            anonymous:  ~
        back_office:
            pattern:    ^/admin
            anonymous:  ~
            form_login:
                provider:                       bigfoot
                login_path:                     /admin/login
                check_path:                     /admin/login_check
                always_use_default_target_path: true
                default_target_path:            /admin/
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
            logout:
                path:   /admin/logout
                target: /admin/

    access_control:
        - { path: ^/admin/login,           roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/reset-password,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,                 roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] }
