# 
# more information can be found here http://sonata-project.org/bundles/media
#
sonata_media:
    db_driver:  doctrine_orm # | doctrine_mongodb
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        # define the public base url for the uploaded media
        sonata.media.cdn.server:
            path: /uploads/media 

    filesystem:
        # define where the uploaded file will be stored
        sonata.media.adapter.filesystem.local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        sonata.media.provider.file:
            resizer:    false

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~