# 
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        Sonata Project
    link:         http://sonata-project.org
    description:  Rich Symfony2 bundle's


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~