web:
  build: ./docker/php
  ports:
    - "8080:80"
  links:
    - mariaDB
  environment:
    SYMFONY_ENV: dev
    # see https://registry.hub.docker.com/u/jderusse/dns-gen/
    #- DOMAIN_NAME=thelia.docker
  command: /usr/sbin/apache2ctl -D FOREGROUND
  volumes:
    - .:/var/www/html

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - "8081:80"
  environment:
    MYSQL_ROOT_UNSERNAME: root
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_PORT_3306_TCP_ADDR: maria
    MYSQL_PORT_3306_TCP_PORT: 3306
  links:
    - mariaDB:maria

mariaDB:
  image: mariadb
  environment:
    MYSQL_DATABASE: thelia
    MYSQL_ROOT_PASSWORD: toor
