Sylius\Component\Core\Model\Taxon:
    exclusion_policy: ALL
    xml_root_name: taxon
    properties:
        images:
            expose: true
            type: array
            groups: [Default, Detailed]
